### PR TITLE
Expand README.

### PR DESCRIPTION
**Pull request by dmitrizagidulin**

### CODE REVIEW

**Comment by mattcollier** [comment]
yeah! documentation.  I'm not sure what pattern we want to use to talk about these modules that *can* be used via docker.  I feel like we need clear delineation between *running* the thing via docker and doing development.  So for this PR, I feel like we need a heading for Development.

And then move the `usage` section to the top assuming that most people are just going to want to run the thing with docker.

**Comment by dmitrizagidulin** [comment]
@mattcollier Sure thing, modifying..

**Comment by mattcollier** [comment]
@dmitrizagidulin what do you think about moving usage below background?

**Comment by dmitrizagidulin** [comment]
@mattcollier Sure!

**Review by ccebrecos — APPROVED** [review]

**Review by mattcollier — APPROVED** [review]

**Pull request merged**
